name: Deploy to Firebase Hosting
'on':
  push:
    branches:
      - main
  pull_request:
    # Spustí se pro jakýkoliv Pull Request cílený na větev 'main'
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PODNIKNITO_WEB }}'
          # ZMĚNA: Pokud je to Pull Request, nasadí se na dočasný kanál, jinak na ostrý 'live'
          channelId: '${{ github.event.pull_request.number && format(''pr-{0}'', github.event.pull_request.number) || ''live'' }}'
          projectId: podniknito-web
